export const PERMISSIONS = [
  "societies.read",
  "societies.manage",
  "settings.manage",
  "geo.read",
  "geo.manage",
  "properties.read",
  "properties.manage",
  "households.read",
  "households.manage",
  "residents.read",
  "residents.manage",
  "sensitive_resident_data.read",
  "children_data.read",
  "children_data.manage",
  "professional_data.read",
  "professional_data.manage",
  "taxonomies.manage",
  "businesses.read",
  "businesses.manage",
  "businesses.verify",
  "map.resident_view",
  "map.admin_view",
  "analytics.read",
  "analytics.sensitive_read",
  "exports.create",
  "roles.manage",
  "moderation.manage",
  "audit.read",
  "feed.manage",
  "announcements.manage",
  "events.manage",
  "opportunities.manage",
  "groups.manage",
  "messaging.use",
  "notifications.manage",
  "imports.manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const ROLE_TEMPLATES = {
  platform_super_admin: [...PERMISSIONS],
  society_owner: [...PERMISSIONS],
  society_super_admin: PERMISSIONS.filter((p) => p !== "societies.manage"),
  society_admin: [
    "societies.read",
    "settings.manage",
    "geo.read",
    "geo.manage",
    "properties.read",
    "properties.manage",
    "households.read",
    "households.manage",
    "residents.read",
    "residents.manage",
    "sensitive_resident_data.read",
    "professional_data.read",
    "professional_data.manage",
    "taxonomies.manage",
    "businesses.read",
    "businesses.manage",
    "businesses.verify",
    "map.resident_view",
    "map.admin_view",
    "analytics.read",
    "exports.create",
    "moderation.manage",
    "audit.read",
    "feed.manage",
    "announcements.manage",
    "events.manage",
    "opportunities.manage",
    "groups.manage",
    "messaging.use",
    "imports.manage",
  ],
  community_manager: [
    "societies.read",
    "residents.read",
    "professional_data.read",
    "businesses.read",
    "map.resident_view",
    "analytics.read",
    "feed.manage",
    "announcements.manage",
    "events.manage",
    "groups.manage",
    "opportunities.manage",
    "messaging.use",
    "moderation.manage",
  ],
  data_manager: [
    "societies.read",
    "geo.read",
    "geo.manage",
    "properties.read",
    "properties.manage",
    "households.read",
    "households.manage",
    "residents.read",
    "residents.manage",
    "sensitive_resident_data.read",
    "professional_data.manage",
    "taxonomies.manage",
    "businesses.manage",
    "imports.manage",
    "exports.create",
    "map.admin_view",
    "audit.read",
  ],
  sector_admin: [
    "societies.read",
    "geo.read",
    "properties.read",
    "households.read",
    "residents.read",
    "map.resident_view",
    "announcements.manage",
    "events.manage",
    "messaging.use",
  ],
  moderator: [
    "societies.read",
    "residents.read",
    "feed.manage",
    "moderation.manage",
    "messaging.use",
  ],
  security_staff: [
    "societies.read",
    "geo.read",
    "map.resident_view",
    "events.manage",
    "messaging.use",
  ],
  event_manager: [
    "societies.read",
    "events.manage",
    "announcements.manage",
    "map.resident_view",
    "messaging.use",
  ],
  resident: [
    "societies.read",
    "residents.read",
    "professional_data.read",
    "businesses.read",
    "map.resident_view",
    "messaging.use",
  ],
  guest: ["societies.read", "businesses.read"],
} as const satisfies Record<string, readonly Permission[]>;

export type RoleTemplate = keyof typeof ROLE_TEMPLATES;
