import { societyLngLat } from "./location.js";

function eventPoint(dx: number, dy: number) {
  return { type: "Point" as const, coordinates: societyLngLat(dx, dy) };
}

export const DEMO_COMMUNITY_LIFE = {
  connections: [
    {
      id: "conn_ahmed_sara",
      fromResidentId: "res_ahmed_khan",
      toResidentId: "res_sara_malik",
      status: "accepted",
      message: "Household + community partners",
    },
    {
      id: "conn_ahmed_maryam",
      fromResidentId: "res_ahmed_khan",
      toResidentId: "res_maryam_noor",
      status: "accepted",
      message: "Mentoring React",
    },
    {
      id: "conn_fatima_aisha",
      fromResidentId: "res_fatima_zahra",
      toResidentId: "res_aisha_rauf",
      status: "accepted",
      message: "Education × design collab",
    },
    {
      id: "conn_nadia_hamza",
      fromResidentId: "res_nadia_imran",
      toResidentId: "res_hamza_ali",
      status: "accepted",
      message: "SME accounting support",
    },
    {
      id: "conn_omar_bilal",
      fromResidentId: "res_omar_siddiqui",
      toResidentId: "res_bilal_hussain",
      status: "accepted",
      message: "Property governance",
    },
    {
      id: "conn_usman_zain",
      fromResidentId: "res_usman_raza",
      toResidentId: "res_zain_abbas",
      status: "accepted",
      message: "Trades referral network",
    },
    {
      id: "conn_hana_sara",
      fromResidentId: "res_hana_qureshi",
      toResidentId: "res_sara_malik",
      status: "accepted",
      message: "Health camp partners",
    },
    {
      id: "conn_maryam_aisha",
      fromResidentId: "res_maryam_noor",
      toResidentId: "res_aisha_rauf",
      status: "pending",
      message: "Would love design mentorship",
    },
  ],
  posts: [
    {
      id: "post_medical_camp",
      authorId: "res_sara_malik",
      authorName: "Sara Malik",
      kind: "announcement",
      body: "Free cardiology screening this Saturday at the Community Center, 10am–1pm. Residents welcome; bring prior reports if available.",
      geoAreaId: "area_block_a1",
      isPinned: true,
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      reactionCount: 2,
      commentCount: 1,
    },
    {
      id: "post_react_help",
      authorId: "res_maryam_noor",
      authorName: "Maryam Noor",
      kind: "question",
      body: "Anyone free for a quick React code review this week? Looking for junior-friendly feedback on a small portfolio project.",
      geoAreaId: "area_block_d1",
      isPinned: false,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      reactionCount: 2,
      commentCount: 1,
    },
    {
      id: "post_plaza_hire",
      authorId: "res_hamza_ali",
      authorName: "Hamza Ali",
      kind: "opportunity_share",
      body: "Plaza Market is hiring a part-time evening helper (3 evenings/week). Prefer residents who can start next Monday.",
      geoAreaId: "area_block_d1",
      isPinned: false,
      createdAt: new Date(Date.now() - 18 * 3600000).toISOString(),
      reactionCount: 1,
      commentCount: 1,
    },
    {
      id: "post_park_cleanup",
      authorId: "res_fatima_zahra",
      authorName: "Fatima Zahra",
      kind: "update",
      body: "Sector B weekend park cleanup was a success — thanks to the 14 neighbors who showed up. Next session in two weeks.",
      geoAreaId: "area_block_b1",
      isPinned: false,
      createdAt: new Date(Date.now() - 8 * 3600000).toISOString(),
      reactionCount: 1,
      commentCount: 0,
    },
    {
      id: "post_tax_clinic",
      authorId: "res_nadia_imran",
      authorName: "Nadia Imran",
      kind: "announcement",
      body: "Hosting a free SME tax Q&A next Thursday evening at Office Suite E-03. Limited to 12 slots.",
      geoAreaId: "area_sector_e",
      isPinned: false,
      createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
      reactionCount: 1,
      commentCount: 0,
    },
    {
      id: "post_electrical_tip",
      authorId: "res_usman_raza",
      authorName: "Usman Raza",
      kind: "update",
      body: "Monsoon tip: if your outdoor junction boxes look damp, message me — I can do a quick safety check for society residents.",
      geoAreaId: "area_sector_e",
      isPinned: false,
      createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
      reactionCount: 0,
      commentCount: 0,
    },
  ],
  events: [
    {
      id: "evt_medical_camp",
      hostId: "res_sara_malik",
      hostName: "Sara Malik",
      title: "Cardiology Screening Camp",
      summary: "Free resident health screening",
      locationName: "Community Center Hall",
      geoAreaId: "area_block_a1",
      startsAt: new Date(Date.now() + 3 * 86400000).toISOString(),
      capacity: 80,
      goingCount: 2,
      interestedCount: 0,
      geomJson: eventPoint(0.001, -0.002),
    },
    {
      id: "evt_tax_clinic",
      hostId: "res_nadia_imran",
      hostName: "Nadia Imran",
      title: "SME Tax Q&A",
      summary: "Evening clinic for local business owners",
      locationName: "Office Suite E-03",
      geoAreaId: "area_sector_e",
      startsAt: new Date(Date.now() + 6 * 86400000).toISOString(),
      capacity: 12,
      goingCount: 1,
      interestedCount: 1,
      geomJson: eventPoint(0.012, -0.004),
    },
    {
      id: "evt_park_cleanup",
      hostId: "res_fatima_zahra",
      hostName: "Fatima Zahra",
      title: "Sector B Park Cleanup",
      summary: "Volunteer morning cleanup",
      locationName: "Sector B Central Park",
      geoAreaId: "area_block_b1",
      startsAt: new Date(Date.now() + 10 * 86400000).toISOString(),
      capacity: 40,
      goingCount: 1,
      interestedCount: 0,
      geomJson: eventPoint(-0.002, 0.003),
    },
    {
      id: "evt_youth_coding",
      hostId: "res_ahmed_khan",
      hostName: "Ahmed Khan",
      title: "Youth Coding Meetup",
      summary: "Intro React session for teens",
      locationName: "School Lab · Sector C",
      geoAreaId: "area_sector_c",
      startsAt: new Date(Date.now() + 14 * 86400000).toISOString(),
      capacity: 25,
      goingCount: 2,
      interestedCount: 0,
      geomJson: eventPoint(-0.009, 0.007),
    },
    {
      id: "evt_trades_fair",
      hostId: "res_usman_raza",
      hostName: "Usman Raza",
      title: "Trades & Home Services Fair",
      summary: "Meet local electricians, plumbers, and contractors",
      locationName: "Near Gate 2",
      geoAreaId: "area_block_a1",
      startsAt: new Date(Date.now() + 21 * 86400000).toISOString(),
      capacity: 100,
      goingCount: 1,
      interestedCount: 0,
      geomJson: eventPoint(-0.004, -0.0082),
    },
    {
      id: "evt_dental_day",
      hostId: "res_hana_qureshi",
      hostName: "Hana Qureshi",
      title: "Family Dental Awareness Day",
      summary: "Oral health tips and free checkups",
      locationName: "SmileCare Dental",
      geoAreaId: "area_sector_c",
      startsAt: new Date(Date.now() + 28 * 86400000).toISOString(),
      capacity: 30,
      goingCount: 0,
      interestedCount: 0,
      geomJson: eventPoint(-0.006, -0.004),
    },
  ],
  opportunities: [
    {
      id: "opp_plaza_helper",
      posterId: "res_hamza_ali",
      posterName: "Hamza Ali",
      kind: "job",
      status: "open",
      title: "Part-time Plaza Market Helper",
      summary: "Evening retail support 3 days/week",
      compensation: "PKR stipend · evenings",
      isRemoteOk: false,
      applicationCount: 0,
    },
    {
      id: "opp_react_junior",
      posterId: "res_ahmed_khan",
      posterName: "Ahmed Khan",
      kind: "freelance",
      status: "open",
      title: "Junior React Assist",
      summary: "Short freelance UI polish for a community tool",
      compensation: "Paid micro-project",
      isRemoteOk: true,
      applicationCount: 1,
    },
    {
      id: "opp_math_tutor",
      posterId: "res_fatima_zahra",
      posterName: "Fatima Zahra",
      kind: "freelance",
      status: "open",
      title: "Weekend Math Tutor",
      summary: "Secondary school tutoring",
      compensation: "Hourly",
      isRemoteOk: false,
      applicationCount: 0,
    },
    {
      id: "opp_mentorship_design",
      posterId: "res_aisha_rauf",
      posterName: "Aisha Rauf",
      kind: "mentorship",
      status: "open",
      title: "Product Design Mentorship",
      summary: "Portfolio reviews for aspiring designers",
      compensation: "Volunteer mentorship",
      isRemoteOk: true,
      applicationCount: 1,
    },
    {
      id: "opp_volunteer_camp",
      posterId: "res_sara_malik",
      posterName: "Sara Malik",
      kind: "volunteer",
      status: "open",
      title: "Medical Camp Volunteers",
      summary: "Registration desk + crowd flow",
      compensation: "Volunteer",
      isRemoteOk: false,
      applicationCount: 1,
    },
    {
      id: "opp_electrical_apprentice",
      posterId: "res_usman_raza",
      posterName: "Usman Raza",
      kind: "internship",
      status: "open",
      title: "Electrical Apprentice Shadow",
      summary: "Learn residential electrical safety",
      compensation: "Unpaid learning + stipend for travel",
      isRemoteOk: false,
      applicationCount: 0,
    },
  ],
};
