export type DemoResident = {
  id: string;
  fullName: string;
  preferredName: string | null;
  email: string | null;
  phone: string | null;
  status: string;
  geoAreaId: string | null;
  headline: string | null;
  bio: string | null;
  employmentStatus: string;
  yearsExperience: number | null;
  openToNetworking: boolean;
  openToMentoring: boolean;
  lookingForWork: boolean;
  openToConsulting: boolean;
  openToFreelance: boolean;
  hiring: boolean;
  volunteerAvail: boolean;
  profileCompleteness: number;
  primaryProfession: string | null;
  professionKeys: string[];
  skills: string[];
  professions: Array<{
    title: string | null;
    label: string;
    categoryLabel: string | null;
    isPrimary: boolean;
  }>;
  employment: Array<{
    employer: string | null;
    jobTitle: string;
    isCurrent: boolean;
    startYear: number | null;
  }>;
};

export const DEMO_PEOPLE = {
  areaNames: [
    { id: "area_block_a1", name: "Block A1" },
    { id: "area_block_a2", name: "Block A2" },
    { id: "area_block_b1", name: "Block B1" },
    { id: "area_block_b2", name: "Block B2" },
    { id: "area_block_d1", name: "Block D1" },
    { id: "area_sector_c", name: "Sector C" },
    { id: "area_sector_e", name: "Sector E" },
  ],
  categories: [
    {
      id: "pcat_healthcare",
      key: "healthcare",
      label: "Medical & Healthcare",
      sortOrder: 1,
      professions: [
        { id: "prof_doctor", key: "doctor", label: "Doctor" },
        { id: "prof_dentist", key: "dentist", label: "Dentist" },
        { id: "prof_nurse", key: "nurse", label: "Nurse" },
      ],
    },
    {
      id: "pcat_technology",
      key: "technology",
      label: "Technology",
      sortOrder: 2,
      professions: [
        { id: "prof_software_engineer", key: "software_engineer", label: "Software Engineer" },
        { id: "prof_product_manager", key: "product_manager", label: "Product Manager" },
        { id: "prof_designer", key: "designer", label: "Designer" },
      ],
    },
    {
      id: "pcat_business",
      key: "business",
      label: "Business",
      sortOrder: 3,
      professions: [
        { id: "prof_entrepreneur", key: "entrepreneur", label: "Entrepreneur" },
        { id: "prof_accountant", key: "accountant", label: "Accountant" },
      ],
    },
    {
      id: "pcat_education",
      key: "education",
      label: "Education",
      sortOrder: 4,
      professions: [
        { id: "prof_teacher", key: "teacher", label: "Teacher" },
        { id: "prof_tutor", key: "tutor", label: "Tutor" },
      ],
    },
    {
      id: "pcat_legal",
      key: "legal",
      label: "Legal",
      sortOrder: 5,
      professions: [{ id: "prof_lawyer", key: "lawyer", label: "Lawyer" }],
    },
    {
      id: "pcat_engineering",
      key: "engineering",
      label: "Engineering",
      sortOrder: 6,
      professions: [{ id: "prof_civil_engineer", key: "civil_engineer", label: "Civil Engineer" }],
    },
    {
      id: "pcat_trades",
      key: "trades",
      label: "Skilled Trades",
      sortOrder: 7,
      professions: [
        { id: "prof_electrician", key: "electrician", label: "Electrician" },
        { id: "prof_plumber", key: "plumber", label: "Plumber" },
      ],
    },
  ],
  households: [
    {
      id: "hh_a1_12",
      label: "Household A1-12",
      propertyId: "prop_a1_12",
      householdSize: 4,
      primaryResidentId: "res_ahmed_khan",
    },
    {
      id: "hh_a1_18",
      label: "Household A1-18",
      propertyId: "prop_a1_18",
      householdSize: 3,
      primaryResidentId: "res_bilal_hussain",
    },
    {
      id: "hh_b1_22",
      label: "Household B1-22",
      propertyId: "prop_b1_22",
      householdSize: 5,
      primaryResidentId: "res_fatima_zahra",
    },
    {
      id: "hh_b1_31",
      label: "Household B1-31",
      propertyId: "prop_b1_31",
      householdSize: 2,
      primaryResidentId: "res_aisha_rauf",
    },
    {
      id: "hh_d1_09",
      label: "Household D1-09",
      propertyId: "prop_d1_09",
      householdSize: 3,
      primaryResidentId: "res_hamza_ali",
    },
    {
      id: "hh_e_03",
      label: "Household E-03",
      propertyId: "prop_e_03",
      householdSize: 4,
      primaryResidentId: "res_nadia_imran",
    },
    {
      id: "hh_e_21",
      label: "Household E-21",
      propertyId: "prop_e_21",
      householdSize: 2,
      primaryResidentId: "res_usman_raza",
    },
    {
      id: "hh_d1_16",
      label: "Household D1-16",
      propertyId: "prop_d1_16",
      householdSize: 1,
      primaryResidentId: "res_maryam_noor",
    },
  ],
  memberships: [
    { householdId: "hh_a1_12", residentId: "res_ahmed_khan", role: "head", isPrimary: true },
    { householdId: "hh_a1_12", residentId: "res_sara_malik", role: "spouse", isPrimary: false },
    { householdId: "hh_a1_18", residentId: "res_bilal_hussain", role: "head", isPrimary: true },
    { householdId: "hh_b1_22", residentId: "res_fatima_zahra", role: "head", isPrimary: true },
    { householdId: "hh_b1_22", residentId: "res_omar_siddiqui", role: "spouse", isPrimary: false },
    { householdId: "hh_b1_31", residentId: "res_aisha_rauf", role: "head", isPrimary: true },
    { householdId: "hh_d1_09", residentId: "res_hamza_ali", role: "head", isPrimary: true },
    { householdId: "hh_e_03", residentId: "res_nadia_imran", role: "head", isPrimary: true },
    { householdId: "hh_e_21", residentId: "res_usman_raza", role: "head", isPrimary: true },
    { householdId: "hh_d1_16", residentId: "res_maryam_noor", role: "head", isPrimary: true },
  ],
  residents: [
    {
      id: "res_ahmed_khan",
      fullName: "Ahmed Khan",
      preferredName: "Ahmed",
      email: "ahmed.khan@example.com",
      phone: "+92-300-1110001",
      status: "active",
      geoAreaId: "area_block_a1",
      headline: "Software Engineering Manager",
      bio: "Builds community tech initiatives and mentors juniors.",
      employmentStatus: "employed",
      yearsExperience: 12,
      openToNetworking: true,
      openToMentoring: true,
      lookingForWork: false,
      openToConsulting: true,
      openToFreelance: false,
      hiring: false,
      volunteerAvail: true,
      profileCompleteness: 92,
      primaryProfession: "Software Engineering Manager",
      professionKeys: ["software_engineer"],
      skills: ["React", "Node.js", "Mentoring"],
      professions: [
        {
          title: "Software Engineering Manager",
          label: "Software Engineer",
          categoryLabel: "Technology",
          isPrimary: true,
        },
      ],
      employment: [
        { employer: "Karachi Tech Collective", jobTitle: "Engineering Manager", isCurrent: true, startYear: 2019 },
      ],
    },
    {
      id: "res_sara_malik",
      fullName: "Sara Malik",
      preferredName: "Sara",
      email: "sara.malik@example.com",
      phone: "+92-300-1110002",
      status: "active",
      geoAreaId: "area_block_a1",
      headline: "Cardiologist",
      bio: "Consultant cardiologist serving the society medical camp.",
      employmentStatus: "employed",
      yearsExperience: 15,
      openToNetworking: true,
      openToMentoring: true,
      lookingForWork: false,
      openToConsulting: true,
      openToFreelance: false,
      hiring: false,
      volunteerAvail: true,
      profileCompleteness: 88,
      primaryProfession: "Cardiologist",
      professionKeys: ["doctor"],
      skills: ["Cardiology", "Mentoring"],
      professions: [
        { title: "Cardiologist", label: "Doctor", categoryLabel: "Medical & Healthcare", isPrimary: true },
      ],
      employment: [
        { employer: "City Heart Clinic", jobTitle: "Consultant Cardiologist", isCurrent: true, startYear: 2014 },
      ],
    },
    {
      id: "res_bilal_hussain",
      fullName: "Bilal Hussain",
      preferredName: "Bilal",
      email: "bilal.hussain@example.com",
      phone: "+92-300-1110003",
      status: "active",
      geoAreaId: "area_block_a2",
      headline: "Civil Engineer",
      bio: "Infrastructure and housing society planning.",
      employmentStatus: "employed",
      yearsExperience: 10,
      openToNetworking: true,
      openToMentoring: false,
      lookingForWork: false,
      openToConsulting: true,
      openToFreelance: false,
      hiring: false,
      volunteerAvail: false,
      profileCompleteness: 80,
      primaryProfession: "Civil Engineer",
      professionKeys: ["civil_engineer"],
      skills: [],
      professions: [
        { title: "Civil Engineer", label: "Civil Engineer", categoryLabel: "Engineering", isPrimary: true },
      ],
      employment: [
        { employer: "Horizon Infrastructure", jobTitle: "Project Engineer", isCurrent: true, startYear: 2018 },
      ],
    },
    {
      id: "res_fatima_zahra",
      fullName: "Fatima Zahra",
      preferredName: "Fatima",
      email: "fatima.zahra@example.com",
      phone: "+92-300-1110004",
      status: "active",
      geoAreaId: "area_block_b1",
      headline: "Mathematics Teacher",
      bio: "Secondary school educator and weekend tutor.",
      employmentStatus: "employed",
      yearsExperience: 8,
      openToNetworking: true,
      openToMentoring: true,
      lookingForWork: false,
      openToConsulting: false,
      openToFreelance: true,
      hiring: false,
      volunteerAvail: true,
      profileCompleteness: 85,
      primaryProfession: "Mathematics Teacher",
      professionKeys: ["teacher", "tutor"],
      skills: ["Teaching", "Mentoring"],
      professions: [
        { title: "Mathematics Teacher", label: "Teacher", categoryLabel: "Education", isPrimary: true },
        { title: "Weekend Tutor", label: "Tutor", categoryLabel: "Education", isPrimary: false },
      ],
      employment: [
        { employer: "Jaffar High School", jobTitle: "Mathematics Teacher", isCurrent: true, startYear: 2017 },
      ],
    },
    {
      id: "res_omar_siddiqui",
      fullName: "Omar Siddiqui",
      preferredName: "Omar",
      email: "omar.siddiqui@example.com",
      phone: "+92-300-1110005",
      status: "active",
      geoAreaId: "area_block_b1",
      headline: "Property Lawyer",
      bio: "Specializes in property and society governance matters.",
      employmentStatus: "self_employed",
      yearsExperience: 14,
      openToNetworking: true,
      openToMentoring: false,
      lookingForWork: false,
      openToConsulting: true,
      openToFreelance: true,
      hiring: false,
      volunteerAvail: false,
      profileCompleteness: 90,
      primaryProfession: "Property Lawyer",
      professionKeys: ["lawyer"],
      skills: ["Property Law"],
      professions: [
        { title: "Property Lawyer", label: "Lawyer", categoryLabel: "Legal", isPrimary: true },
      ],
      employment: [
        { employer: "Siddiqui & Co.", jobTitle: "Principal Advocate", isCurrent: true, startYear: 2012 },
      ],
    },
    {
      id: "res_aisha_rauf",
      fullName: "Aisha Rauf",
      preferredName: "Aisha",
      email: "aisha.rauf@example.com",
      phone: "+92-300-1110006",
      status: "active",
      geoAreaId: "area_block_b1",
      headline: "Product Designer",
      bio: "Design systems and community product UX.",
      employmentStatus: "employed",
      yearsExperience: 6,
      openToNetworking: true,
      openToMentoring: true,
      lookingForWork: false,
      openToConsulting: false,
      openToFreelance: true,
      hiring: false,
      volunteerAvail: false,
      profileCompleteness: 78,
      primaryProfession: "Product Designer",
      professionKeys: ["designer"],
      skills: ["UI/UX Design", "React"],
      professions: [
        { title: "Product Designer", label: "Designer", categoryLabel: "Technology", isPrimary: true },
      ],
      employment: [
        { employer: "Northwind Labs", jobTitle: "Product Designer", isCurrent: true, startYear: 2021 },
      ],
    },
    {
      id: "res_hamza_ali",
      fullName: "Hamza Ali",
      preferredName: "Hamza",
      email: "hamza.ali@example.com",
      phone: "+92-300-1110007",
      status: "active",
      geoAreaId: "area_block_d1",
      headline: "Entrepreneur · Plaza Market",
      bio: "Owns a retail business and occasionally hires part-time staff.",
      employmentStatus: "self_employed",
      yearsExperience: 9,
      openToNetworking: true,
      openToMentoring: false,
      lookingForWork: false,
      openToConsulting: false,
      openToFreelance: false,
      hiring: true,
      volunteerAvail: true,
      profileCompleteness: 84,
      primaryProfession: "Entrepreneur",
      professionKeys: ["entrepreneur"],
      skills: [],
      professions: [
        { title: "Entrepreneur", label: "Entrepreneur", categoryLabel: "Business", isPrimary: true },
      ],
      employment: [
        { employer: "Plaza Market Store", jobTitle: "Owner", isCurrent: true, startYear: 2018 },
      ],
    },
    {
      id: "res_nadia_imran",
      fullName: "Nadia Imran",
      preferredName: "Nadia",
      email: "nadia.imran@example.com",
      phone: "+92-300-1110008",
      status: "active",
      geoAreaId: "area_sector_e",
      headline: "Chartered Accountant",
      bio: "Tax and SME accounting advisory.",
      employmentStatus: "self_employed",
      yearsExperience: 11,
      openToNetworking: true,
      openToMentoring: true,
      lookingForWork: false,
      openToConsulting: true,
      openToFreelance: true,
      hiring: false,
      volunteerAvail: false,
      profileCompleteness: 87,
      primaryProfession: "Chartered Accountant",
      professionKeys: ["accountant"],
      skills: ["Accounting"],
      professions: [
        { title: "Chartered Accountant", label: "Accountant", categoryLabel: "Business", isPrimary: true },
      ],
      employment: [
        { employer: "Imran Advisory", jobTitle: "Principal CA", isCurrent: true, startYear: 2015 },
      ],
    },
    {
      id: "res_usman_raza",
      fullName: "Usman Raza",
      preferredName: "Usman",
      email: "usman.raza@example.com",
      phone: "+92-300-1110009",
      status: "active",
      geoAreaId: "area_sector_e",
      headline: "Electrician",
      bio: "Residential electrical services within the society.",
      employmentStatus: "self_employed",
      yearsExperience: 7,
      openToNetworking: true,
      openToMentoring: false,
      lookingForWork: false,
      openToConsulting: false,
      openToFreelance: true,
      hiring: false,
      volunteerAvail: true,
      profileCompleteness: 75,
      primaryProfession: "Electrician",
      professionKeys: ["electrician"],
      skills: ["Electrical Work"],
      professions: [
        { title: "Electrician", label: "Electrician", categoryLabel: "Skilled Trades", isPrimary: true },
      ],
      employment: [
        { employer: null, jobTitle: "Licensed Electrician", isCurrent: true, startYear: 2019 },
      ],
    },
    {
      id: "res_maryam_noor",
      fullName: "Maryam Noor",
      preferredName: "Maryam",
      email: "maryam.noor@example.com",
      phone: "+92-300-1110010",
      status: "active",
      geoAreaId: "area_block_d1",
      headline: "Junior Developer",
      bio: "Looking for React opportunities and mentorship.",
      employmentStatus: "looking_for_work",
      yearsExperience: 2,
      openToNetworking: true,
      openToMentoring: false,
      lookingForWork: true,
      openToConsulting: false,
      openToFreelance: true,
      hiring: false,
      volunteerAvail: false,
      profileCompleteness: 70,
      primaryProfession: "Junior Developer",
      professionKeys: ["software_engineer"],
      skills: ["React", "Node.js"],
      professions: [
        {
          title: "Junior Developer",
          label: "Software Engineer",
          categoryLabel: "Technology",
          isPrimary: true,
        },
      ],
      employment: [
        { employer: "Freelance", jobTitle: "Frontend Developer", isCurrent: true, startYear: 2024 },
      ],
    },
    {
      id: "res_zain_abbas",
      fullName: "Zain Abbas",
      preferredName: "Zain",
      email: "zain.abbas@example.com",
      phone: "+92-300-1110011",
      status: "active",
      geoAreaId: "area_block_b2",
      headline: "Licensed Plumber",
      bio: "Emergency and scheduled plumbing work.",
      employmentStatus: "self_employed",
      yearsExperience: 13,
      openToNetworking: true,
      openToMentoring: false,
      lookingForWork: false,
      openToConsulting: false,
      openToFreelance: true,
      hiring: false,
      volunteerAvail: true,
      profileCompleteness: 72,
      primaryProfession: "Licensed Plumber",
      professionKeys: ["plumber"],
      skills: ["Plumbing"],
      professions: [
        { title: "Licensed Plumber", label: "Plumber", categoryLabel: "Skilled Trades", isPrimary: true },
      ],
      employment: [
        { employer: null, jobTitle: "Plumber", isCurrent: true, startYear: 2013 },
      ],
    },
    {
      id: "res_hana_qureshi",
      fullName: "Hana Qureshi",
      preferredName: "Hana",
      email: "hana.qureshi@example.com",
      phone: "+92-300-1110012",
      status: "active",
      geoAreaId: "area_sector_c",
      headline: "Dentist",
      bio: "Family dental care and oral health awareness.",
      employmentStatus: "employed",
      yearsExperience: 9,
      openToNetworking: true,
      openToMentoring: true,
      lookingForWork: false,
      openToConsulting: false,
      openToFreelance: false,
      hiring: false,
      volunteerAvail: true,
      profileCompleteness: 83,
      primaryProfession: "Dentist",
      professionKeys: ["dentist"],
      skills: ["Mentoring"],
      professions: [
        { title: "Dentist", label: "Dentist", categoryLabel: "Medical & Healthcare", isPrimary: true },
      ],
      employment: [
        { employer: "SmileCare Dental", jobTitle: "Associate Dentist", isCurrent: true, startYear: 2018 },
      ],
    },
  ] satisfies DemoResident[],
};
